name: Build LineageOS Kernel

on:
  workflow_dispatch:
    inputs:
      rom_source:
        description: "ROM Kernel Source Code"
        required: true
        type: choice
        options:
          - LineageOS
          - Crdroid
          - PixelOS

      ksu_type:
        description: "KernelSU Version"
        required: true
        type: choice
        options:
          - KernelSU-Official
          - ReSukiSU
          - KernelSU-Next
          - KernelSU-Official-susfs
          - KernelSU-backslashxx-susfs
          - KernelSU-Next-susfs
          - ReSukiSU-susfs
          - None

      lz4_enable:
        description: "Enable lz4 1.10.0 patch"
        required: true
        type: boolean
        default: true

      netfilter:
        description: "Enable IPSET & IPv6_NAT"
        required: true
        type: boolean
        default: true

      ccm:
        description: "Enable BBR & ECN"
        required: true
        type: boolean
        default: true

      droidspaces:
        description: "Droidspaces Container Support"
        required: true
        type: choice
        options:
          - "none"
          - "standard"
          - "extended"

      docker:
        description: "Docker Container Support"
        required: true
        type: boolean
        default: false

      docker_net:
        description: "Docker advanced networking (bridge/nftables/IPVS). Off = core only"
        required: false
        type: boolean
        default: true

      vm:
        description: "Virtual Machine (KVM) Support"
        required: true
        type: boolean
        default: false

      kernel_name:
        description: "Custom Kernel Name"
        required: false
        type: string
        default: ""

      create_release:
        description: "Create GitHub Release"
        required: true
        type: boolean
        default: true

permissions:
  actions: read
  checks: read
  contents: write

jobs:
  build:
    uses: ./.github/workflows/_build-kernel.yml
    with:
      rom_source: ${{ inputs.rom_source }}
      ksu_type: ${{ inputs.ksu_type }}
      lz4_enable: ${{ inputs.lz4_enable }}
      netfilter: ${{ inputs.netfilter }}
      ccm: ${{ inputs.ccm }}
      droidspaces: ${{ inputs.droidspaces }}
      docker: ${{ inputs.docker }}
      docker_net: ${{ inputs.docker_net }}
      vm: ${{ inputs.vm }}
      kernel_name: ${{ inputs.kernel_name }}
      create_release: ${{ inputs.create_release }}
    secrets: inherit
