name: Build YAAP Kernel

on:
  workflow_dispatch:
    inputs:
      yaap_version:
        description: "YAAP Version"
        required: true
        type: choice
        options:
          - YAAP-17
          - YAAP-16

      ksu_type:
        description: "KernelSU Version"
        required: true
        type: choice
        options:
          - KernelSU-Official
          - ReSukiSU
          - KernelSU-Next
          - KernelSU-Official-susfs
          - KernelSU-backslashxx-susfs
          - KernelSU-Next-susfs
          - ReSukiSU-susfs
          - None

      netfilter:
        description: "Enable IPSET & IPv6_NAT"
        required: true
        type: boolean
        default: true

      ccm:
        description: "Enable BBR & ECN"
        required: true
        type: boolean
        default: true

      docker:
        description: "Docker Container Support"
        required: true
        type: boolean
        default: false

      vm:
        description: "Virtual Machine (KVM) Support"
        required: true
        type: boolean
        default: false

      kernel_name:
        description: "Custom Kernel Name"
        required: false
        type: string
        default: ""

      create_release:
        description: "Create GitHub Release"
        required: true
        type: boolean
        default: true

permissions:
  actions: read
  checks: read
  contents: write

jobs:
  build:
    uses: ./.github/workflows/_build-kernel.yml
    with:
      rom_source: ${{ inputs.yaap_version }}
      ksu_type: ${{ inputs.ksu_type }}
      lz4_enable: false
      netfilter: ${{ inputs.netfilter }}
      ccm: ${{ inputs.ccm }}
      droidspaces: none
      docker: ${{ inputs.docker }}
      vm: ${{ inputs.vm }}
      kernel_name: ${{ inputs.kernel_name }}
      create_release: ${{ inputs.create_release }}
    secrets: inherit
